name: aws_docker_demo
description: AWS Full Stack Demo with Flutter, Spring Boot, and MySQL
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # HTTP 통신
  http: ^1.1.0
  
  # UI 컴포넌트
  cupertino_icons: ^1.0.6
  
  # 애니메이션 및 UI 개선
  animated_text_kit: ^4.2.2  # 텍스트 애니메이션
  shimmer: ^3.0.0           # 로딩 효과

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # 린트 규칙
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true